// tweaks-panel.jsx
const __TWEAKS_STYLE = `
  .twk-panel{position:fixed;right:16px;bottom:16px;z-index:2147483646;width:280px;max-height:calc(100vh - 32px);display:flex;flex-direction:column;transform:scale(var(--dc-inv-zoom,1));transform-origin:bottom right;background:rgba(250,249,247,.78);color:#29261b;-webkit-backdrop-filter:blur(24px) saturate(160%);backdrop-filter:blur(24px) saturate(160%);border:.5px solid rgba(255,255,255,.6);border-radius:14px;box-shadow:0 1px 0 rgba(255,255,255,.5) inset,0 12px 40px rgba(0,0,0,.18);font:11.5px/1.4 ui-sans-serif,system-ui,-apple-system,sans-serif;overflow:hidden}
  .twk-hd{display:flex;align-items:center;justify-content:space-between;padding:10px 8px 10px 14px;cursor:move;user-select:none}
  .twk-hd b{font-size:12px;font-weight:600;letter-spacing:.01em}
  .twk-x{appearance:none;border:0;background:transparent;color:rgba(41,38,27,.55);width:22px;height:22px;border-radius:6px;cursor:default;font-size:13px;line-height:1}
  .twk-x:hover{background:rgba(0,0,0,.06);color:#29261b}
  .twk-body{padding:2px 14px 14px;display:flex;flex-direction:column;gap:10px;overflow-y:auto;overflow-x:hidden;min-height:0}
  .twk-row{display:flex;flex-direction:column;gap:5px}
  .twk-row-h{flex-direction:row;align-items:center;justify-content:space-between;gap:10px}
  .twk-lbl{display:flex;justify-content:space-between;align-items:baseline;color:rgba(41,38,27,.72)}
  .twk-lbl>span:first-child{font-weight:500}
  .twk-sect{font-size:10px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:rgba(41,38,27,.45);padding:10px 0 0}
  .twk-sect:first-child{padding-top:0}
  .twk-toggle{position:relative;width:32px;height:18px;border:0;border-radius:999px;background:rgba(0,0,0,.15);transition:background .15s;cursor:default;padding:0}
  .twk-toggle[data-on="1"]{background:#34c759}
  .twk-toggle i{position:absolute;top:2px;left:2px;width:14px;height:14px;border-radius:50%;background:#fff;box-shadow:0 1px 2px rgba(0,0,0,.25);transition:transform .15s}
  .twk-toggle[data-on="1"] i{transform:translateX(14px)}
  .twk-seg{position:relative;display:flex;padding:2px;border-radius:8px;background:rgba(0,0,0,.06);user-select:none}
  .twk-seg-thumb{position:absolute;top:2px;bottom:2px;border-radius:6px;background:rgba(255,255,255,.9);box-shadow:0 1px 2px rgba(0,0,0,.12);transition:left .15s cubic-bezier(.3,.7,.4,1),width .15s}
  .twk-seg button{appearance:none;position:relative;z-index:1;flex:1;border:0;background:transparent;color:inherit;font:inherit;font-weight:500;min-height:22px;border-radius:6px;cursor:default;padding:4px 6px;line-height:1.2}
  .twk-chips{display:flex;gap:6px}
  .twk-chip{position:relative;appearance:none;flex:1;min-width:0;height:46px;padding:0;border:0;border-radius:6px;overflow:hidden;cursor:default;box-shadow:0 0 0 .5px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.06);transition:transform .12s,box-shadow .12s}
  .twk-chip:hover{transform:translateY(-1px);box-shadow:0 0 0 .5px rgba(0,0,0,.18),0 4px 10px rgba(0,0,0,.12)}
  .twk-chip[data-on="1"]{box-shadow:0 0 0 1.5px rgba(0,0,0,.85),0 2px 6px rgba(0,0,0,.15)}
  .twk-chip svg{position:absolute;top:6px;left:6px;width:13px;height:13px;filter:drop-shadow(0 1px 1px rgba(0,0,0,.3))}
`;
function useTweaks(defaults){const[values,setValues]=React.useState(defaults);const setTweak=React.useCallback((k,v)=>{const edits=typeof k==='object'&&k!==null?k:{[k]:v};setValues(p=>({...p,...edits}));window.parent.postMessage({type:'__edit_mode_set_keys',edits},'*');window.dispatchEvent(new CustomEvent('tweakchange',{detail:edits}));});return[values,setTweak];}
function TweaksPanel({title='Tweaks',children}){const[open,setOpen]=React.useState(false);const dragRef=React.useRef(null);const offsetRef=React.useRef({x:16,y:16});const PAD=16;const clamp=React.useCallback(()=>{const p=dragRef.current;if(!p)return;const w=p.offsetWidth,h=p.offsetHeight;const mr=Math.max(PAD,window.innerWidth-w-PAD),mb=Math.max(PAD,window.innerHeight-h-PAD);offsetRef.current={x:Math.min(mr,Math.max(PAD,offsetRef.current.x)),y:Math.min(mb,Math.max(PAD,offsetRef.current.y))};p.style.right=offsetRef.current.x+'px';p.style.bottom=offsetRef.current.y+'px';});React.useEffect(()=>{if(!open)return;clamp();const ro=new ResizeObserver(clamp);ro.observe(document.documentElement);return()=>ro.disconnect();},[open,clamp]);React.useEffect(()=>{const h=e=>{const t=e?.data?.type;if(t==='__activate_edit_mode')setOpen(true);else if(t==='__deactivate_edit_mode')setOpen(false);};window.addEventListener('message',h);window.parent.postMessage({type:'__edit_mode_available'},'*');return()=>window.removeEventListener('message',h);},[]);const dismiss=()=>{setOpen(false);window.parent.postMessage({type:'__edit_mode_dismissed'},'*');};const onDrag=e=>{const p=dragRef.current;if(!p)return;const r=p.getBoundingClientRect();const sx=e.clientX,sy=e.clientY,sr=window.innerWidth-r.right,sb=window.innerHeight-r.bottom;const mv=ev=>{offsetRef.current={x:sr-(ev.clientX-sx),y:sb-(ev.clientY-sy)};clamp();};const up=()=>{window.removeEventListener('mousemove',mv);window.removeEventListener('mouseup',up);};window.addEventListener('mousemove',mv);window.addEventListener('mouseup',up);};if(!open)return null;return(<><style>{__TWEAKS_STYLE}</style><div ref={dragRef} className="twk-panel" style={{right:offsetRef.current.x,bottom:offsetRef.current.y}}><div className="twk-hd" onMouseDown={onDrag}><b>{title}</b><button className="twk-x" onMouseDown={e=>e.stopPropagation()} onClick={dismiss}>✕</button></div><div className="twk-body">{children}</div></div></>);}
function TweakSection({title,children}){return(<><div className="twk-sect">{title}</div>{children}</>);}
function TweakToggle({label,value,onChange}){return(<div className="twk-row twk-row-h"><div className="twk-lbl"><span>{label}</span></div><button type="button" className="twk-toggle" data-on={value?'1':'0'} role="switch" aria-checked={!!value} onClick={()=>onChange(!value)}><i/></button></div>);}
function TweakRadio({label,value,options,onChange}){const trackRef=React.useRef(null);const[dragging,setDragging]=React.useState(false);const vRef=React.useRef(value);vRef.current=value;const opts=options.map(o=>Array.isArray(o)?{value:o[0],label:o[1]}:typeof o==='object'?o:{value:o,label:o});const idx=Math.max(0,opts.findIndex(o=>o.value===value));const n=opts.length;const segAt=cx=>{const r=trackRef.current.getBoundingClientRect();return opts[Math.max(0,Math.min(n-1,Math.floor(((cx-r.left-2)/(r.width-4))*n)))].value;};const onPD=e=>{setDragging(true);const v0=segAt(e.clientX);if(v0!==vRef.current)onChange(v0);const mv=ev=>{if(!trackRef.current)return;const v=segAt(ev.clientX);if(v!==vRef.current)onChange(v);};const up=()=>{setDragging(false);window.removeEventListener('pointermove',mv);window.removeEventListener('pointerup',up);};window.addEventListener('pointermove',mv);window.addEventListener('pointerup',up);};return(<div className="twk-row"><div className="twk-lbl"><span>{label}</span></div><div ref={trackRef} role="radiogroup" onPointerDown={onPD} className={dragging?'twk-seg dragging':'twk-seg'}><div className="twk-seg-thumb" style={{left:`calc(2px + ${idx} * (100% - 4px) / ${n})`,width:`calc((100% - 4px) / ${n})`}}/>{opts.map(o=><button key={o.value} type="button" role="radio" aria-checked={o.value===value}>{o.label}</button>)}</div></div>);}
function TweakColor({label,value,options,onChange}){const key=o=>String(JSON.stringify(o)).toLowerCase();const cur=key(value);return(<div className="twk-row"><div className="twk-lbl"><span>{label}</span></div><div className="twk-chips" role="radiogroup">{options.map((o,i)=>{const colors=Array.isArray(o)?o:[o];const[hero]=colors;const on=key(o)===cur;return(<button key={i} type="button" className="twk-chip" role="radio" aria-checked={on} data-on={on?'1':'0'} style={{background:hero}} onClick={()=>onChange(o)}>{on&&<svg viewBox="0 0 14 14" style={{position:'absolute',top:6,left:6,width:13,height:13}}><path d="M3 7.2 5.8 10 11 4.2" fill="none" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" stroke="#fff"/></svg>}</button>);})}</div></div>);}
Object.assign(window,{useTweaks,TweaksPanel,TweakSection,TweakToggle,TweakRadio,TweakColor});